name-template: "Release v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'
categories:
  - title: "🚀 Features"
    labels:
      - feature
      - enhancement
  - title: "🐛 Bug Fixes"
    labels:
      - bug
  - title: "🧰 Maintenance"
    labels:
      - chore
  - title: "Github"
    labels:
      - "area/github"
autolabeler:
  - label: "chore"
    files:
      - "*.md"
    branch:
      - '/docs{0,1}\/.+/'
    title:
      - "/chore/"
  - label: "bug"
    branch:
      - '/fix\/.+/'
    title:
      - "/fix/i"
  - label: "enhancement"
    branch:
      - '/feature\/.+/'
    title:
      - "/feat/"
version-resolver:
  major:
    labels: ["type/break"]
  minor:
    labels: ["type/major", "type/minor"]
  patch:
    labels: ["type/patch"]
  default: patch
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
