mods:
  - screepsmod-auth
  - screepsmod-admin-utils
  - screepsmod-cli
bots:
  simplebot: screepsbot-zeswarm

cli:
  host: 0.0.0.0
  port: 21028

launcherOptions:
  runnerThreads: 1
  processorCount: 1
