name: "Release"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Publish Latest Release
        uses: ivangabriele/publish-latest-release@v3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
